### ISSUE TITLE
Seite Down

### ISSUE THREAD

**Issue by kaisims** [simbo/Anno2070Rechner.de#3]
Die Website selbst ist leider down. Die "Fehlermeldung" ist: 
`111<br />
<b>Warning</b>:  session_start(): Failed to read session data: user (path: /var/lib/php-sessions) in <b>/var/www/virtual/simbo/anno2070rechner.de/inc/class-session.php</b> on line <b>50</b><br />
ERROR: Session::start() failed`

**Comment by ChargingBulle** [comment]
still down

**Comment by simbo** [comment]
that took some time. fixed now.
